# Análise exploratória e scripts computacionais de ati.ipynb

- **Repositório:** `analise-de-dados-fundamentos`  
- **Tecnologias:** Pandas, NumPy  
- **Arquivo Original:** `ati.ipynb`  

---

In [5]:
import pandas as pd

tabela = pd.read_csv("arrecadacao-itr.csv", sep=';', encoding='utf-8')
display(tabela)

,Ano,Mes,Unidade da Federacaoo,Regiao Politica,Cidade e UF,Valor
0,2016,Janeiro,Rond�nia,Norte,Guajar�-Mirim - RO,"75,27"
1,2016,Janeiro,Rond�nia,Norte,Alto Alegre dos Parecis - RO,"22,02"
2,2016,Janeiro,Rond�nia,Norte,Porto Velho - RO,"217.093,63"
3,2016,Janeiro,Rond�nia,Norte,Buritis - RO,"362,22"
4,2016,Janeiro,Rond�nia,Norte,Ji-Paran� - RO,"8.429,21"
...,...,...,...,...,...,...
538704,2024,Janeiro,Santa Catarina,Sul,Serra Alta - SC,"133,76"
538705,2024,Janeiro,Santa Catarina,Sul,Tun�polis - SC,"59,96"
538706,2024,Janeiro,Goi�s,Centro-Oeste,Guarinos - GO,"1.740,05"
538707,2024,Janeiro,Goi�s,Centro-Oeste,Rio Quente - GO,"2.997,85"
538708,2024,Janeiro,Mato Grosso do Sul,Centro-Oeste,Coronel Sapucaia - MS,"32.887,96"

In [6]:
"""

Atividade parte 2

a)Indicar o nome da base
Arrecadação de irt


b)Que tipo de dado (ou problema) caracteriza esta base de dados, ou seja, o que se pode
extrair de conhecimento a partir dos dados lá disponíveis

Pode se extrair o IRT(Imposto sobre os Rendimentos do Trabalho)total das regiões, cidades e estados


c)Indicar quem forneceu esta base, a data da coleta dos dados (início e final), além de
particularidades (por exemplo, a coleta foi interrompida durante um período de tempo
e depois retomada);

A base foi fornecida pelo "portal de dados abertos" fornecida pelo site do governo federal
(link:https://dados.gov.br/dados/conjuntos-dados/resultado-da-arrecadacao) de 2016 á 2024.


d)Quantos atributos (variáveis) a base possui e para cada atributo indicar o tipo: nominal,
ordinal, discreto, contínuo.

Existem 6 variáveis sendo: Ano	Mes	Unidade da Federacaoo Regiao Polotica Cidade e UF	Valor

Variáveis Contínuas: Ano, Mês

Variáveis Discretas:Valor

Variáveis Nominais: Unidade da Federação, Regiao Polotica, Cidade e UF


e)Indicar se existem informações já publicadas sobre seu uso e, em caso positivo, onde foi
publicado, por quem, o quê

Existem informações positivas, uma recente foi publicada pela "Câmara dos deputados" no proprio site
(https://www.camara.leg.br/noticias/997624-comissao-aprova-isencao-de-itr-para-geracao-renovavel-em-propriedade-rural/).
Nesta noticia fala sobre a aprovação aprova isenção de ITR para geração renovável em propriedade rural.

"""

'\n\nAtividade parte 2\n\na)Indicar o nome da base\nArrecadação de irt\n\n\nb)Que tipo de dado (ou problema) caracteriza esta base de dados, ou seja, o que se pode\nextrair de conhecimento a partir dos dados lá disponíveis\n\nPode se extrair o IRT(Imposto sobre os Rendimentos do Trabalho)total das regiões, cidades e estados\n\n\nc)Indicar quem forneceu esta base, a data da coleta dos dados (início e final), além de\nparticularidades (por exemplo, a coleta foi interrompida durante um período de tempo\ne depois retomada);\n\nA base foi fornecida pelo "portal de dados abertos" fornecida pelo site do governo federal \n(link:https://dados.gov.br/dados/conjuntos-dados/resultado-da-arrecadacao) de 2016 á 2024.\n\n\nd)Quantos atributos (variáveis) a base possui e para cada atributo indicar o tipo: nominal,\nordinal, discreto, contínuo.\n\nExistem 6 variáveis sendo: Ano\tMes\tUnidade da Federacaoo Regiao Polotica Cidade e UF\tValor\n\nVariáveis Contínuas: Ano, Mês\n\nVariáveis Discretas:Valor\n\nVariáveis Nominais: Unidade da Federação, Regiao Polotica, Cidade e UF\t\n\n\ne)Indicar se existem informações já publicadas sobre seu uso e, em caso positivo, onde foi\npublicado, por quem, o quê\n\nExistem informações positivas, uma recente foi publicada pela "Câmara dos deputados" no proprio site\n(https://www.camara.leg.br/noticias/997624-comissao-aprova-isencao-de-itr-para-geracao-renovavel-em-propriedade-rural/).\nNesta noticia fala sobre a aprovação aprova isenção de ITR para geração renovável em propriedade rural.\n\n'

In [7]:
curitiba = tabela.loc[(tabela["Cidade e UF"] == "Curitiba - PR") & (tabela["Ano"] == 2023)]
display(curitiba)

,Ano,Mes,Unidade da Federacaoo,Regiao Politica,Cidade e UF,Valor
471434,2023,Janeiro,Paran�,Sul,Curitiba - PR,"54.548,69"
476062,2023,Fevereiro,Paran�,Sul,Curitiba - PR,"43.366,66"
481780,2023,Mar�o,Paran�,Sul,Curitiba - PR,"45.836,28"
487350,2023,Abril,Paran�,Sul,Curitiba - PR,"41.713,73"
492920,2023,Maio,Paran�,Sul,Curitiba - PR,"113.856,00"
498490,2023,Junho,Paran�,Sul,Curitiba - PR,"774.914,96"
504060,2023,Julho,Paran�,Sul,Curitiba - PR,"106.647,87"
509630,2023,Agosto,Paran�,Sul,Curitiba - PR,"81.601,99"
515200,2023,Setembro,Paran�,Sul,Curitiba - PR,"77.109,36"
520770,2023,Outubro,Paran�,Sul,Curitiba - PR,"91.434,01"
526340,2023,Novembro,Paran�,Sul,Curitiba - PR,"156.051,14"
531910,2023,Dezembro,Paran�,Sul,Curitiba - PR,"92.160,90"

In [8]:
import numpy as np
from tabulate import tabulate

curitiba['Valor'] = curitiba['Valor'].astype(str).str.replace(',', '').astype(float)

num_classes = 5

valor_min = curitiba['Valor'].min()
valor_max = curitiba['Valor'].max()

intervalos = np.linspace(valor_min, valor_max + 0.001, num_classes + 1)

frequencias = [(f'{intervalos[i]:.6f} - {intervalos[i+1]:.6f}', ((curitiba['Valor'] >= intervalos[i]) & (curitiba['Valor'] < intervalos[i+1])).sum()) for i in range(num_classes)]

frequencias = [(intervalo, int(frequencia)) for intervalo, frequencia in frequencias]

pontos_medios = [(intervalos[i] + intervalos[i+1]) / 2 for i in range(num_classes)]

frequencias = [(f'{intervalos[i]:.6f} - {intervalos[i+1]:.6f}', pontos_medios[i], int(frequencia)) for i, (intervalo, frequencia) in enumerate(frequencias)]

frequencia_acumulada = 0
frequencias_acumuladas = []
for intervalo, ponto_medio, frequencia in frequencias:
    frequencia_acumulada += frequencia
    frequencias_acumuladas.append((intervalo, ponto_medio, frequencia, frequencia_acumulada))

print(tabulate(frequencias_acumuladas, headers=['frequencias', 'Ponto Médio', 'Intervalo de Classe', 'Frequência Acumulada'], tablefmt='grid'))

+-------------------------+---------------+-----------------------+------------------------+
| frequencias             |   Ponto Médio |   Intervalo de Classe |   Frequência Acumulada |
+=========================+===============+=======================+========================+
| 41.713730 - 188.354176  |       115.034 |                    11 |                     11 |
+-------------------------+---------------+-----------------------+------------------------+
| 188.354176 - 334.994622 |       261.674 |                     0 |                     11 |
+-------------------------+---------------+-----------------------+------------------------+
| 334.994622 - 481.635068 |       408.315 |                     0 |                     11 |
+-------------------------+---------------+-----------------------+------------------------+
| 481.635068 - 628.275514 |       554.955 |                     0 |                     11 |
+-------------------------+---------------+-----------------------+------------------------+
| 628.275514 - 774.915960 |       701.596 |                     1 |                     12 |
+-------------------------+---------------+-----------------------+------------------------+

<ipython-input-8-1761de3e25fe>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  curitiba['Valor'] = curitiba['Valor'].astype(str).str.replace(',', '').astype(float)